### ISSUE TITLE
Question about PacBio data for xTea_pacbio_raw_LINE1_hg38.txt

### ISSUE THREAD

**Issue by YanmingGan** [parklab/xTea_paper#2]
Hi,
Thanks for developing the tool!
I have one question for the output file [xTea_pacbio_raw_LINE1_hg38.txt that could you please also provide the exact version of the PacBio data used to generate the result? Or, is that subread data or contig data?
(https://github.com/parklab/xTea_paper/blob/main/NA12878_L1_cmp/xTea_pacbio_raw_LINE1_hg38.txt)
Thanks.

**Comment by simoncchu** [comment]
Hi, please see the data availability here: https://www.nature.com/articles/s41467-021-24041-8#data-availability. The reads were realigned with minimap2.
